name: Run SonarQube with Maven

on:
  push:
    branches:
      - main
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '17'  # Aquí declaras la versión de Java como variable

    steps:
      - uses: actions/checkout@v3

      # Configuración de Java usando la variable de entorno
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'  # O puedes usar 'adopt' si prefieres esa distribución
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Run tests with Maven
        run: mvn clean verify

      - name: Run SonarQube analysis
        run: mvn sonar:sonar -Dsonar.projectKey=javareachabilityy -Dsonar.organization=javareachabilityy -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
